language: node_js
node_js:
  - 'stable'
services:
  - postgresql
cache:
  directories:
    - "node_modules"

env:
  global:
    - NODE_ENV=test
  
before_script:
  - psql -c 'create database portfolio_test;' -U postgres
  - yarn add sequelize-cli
  - yarn run build
script:
  - yarn test
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.16.0
  - export PATH="$HOME/.yarn/bin:$PATH"
after_success:
  - yarn run coverage